version: '3.8'
services:
    frontend:
        networks:
            - react-express-pj
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/usr/src/app
            - /usr/src/app/node_modules
        container_name: frontend
        build: ./frontend
    backend:
        networks:
            - react-express-pj
            - express-mongo-pj
        volumes:
            - ./backend:/usr/src/app
            - /usr/src/app/node_modules
        container_name: backend
        build: ./backend
    mongo:
        networks:
            - express-mongo-pj
        volumes:
            - ./data:/data/db
        container_name: mongo
        image: mongo:latest
networks:
    express-mongo-pj:
        external: true
    react-express-pj:
        external: true